### ISSUE TITLE
Not recognized by Arduino IDE

### ISSUE THREAD

**Issue by martinrevert** [koendv/xtensa-esp32-elf-raspberrypi#1]
Installed the .deb on Linux raspberrypi4 5.4.79-v8+ #1373 SMP PREEMPT Mon Nov 23 13:32:41 GMT 2020 aarch64 GNU/Linux
but for some reason Arduino IDE warns that the lib is not available on my system when I try to install "ESP32" board lib.

![2021-01-01-164229_1440x900_scrot](https://user-images.githubusercontent.com/955927/103445323-52ca8c80-4c51-11eb-9e94-2cfe762ffc4a.png)

I'm I doing someting wrong besides installing the deb as usual debian package?
Thanks

**Comment by koendv** [comment]
OK. 
If:
- when running raspberry os Buster 64-bit
- I add "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json" to Arduino IDE Files/Preferences/Additional Board Manager urls 
- and I try to install  "esp32" from the arduino boards manager, 
- I get the error "tool mkspiffs is not available for your operating system".

This is not because 'mkspiffs' is not available for raspberry Buster 64-bit. You can compile 'mkspiffs' from git just fine.
To fix this, I would suggest: open an issue at https://github.com/espressif/arduino-esp32/ to
- add a mkspiffs release for aarch64 to https://github.com/igrr/mkspiffs
- add a reference to this build to package_esp32_dev_index.json
